name: scrobblenaut
description: A deadly simple LastFM API Wrapper for Dart. So deadly simple that it's gonna hit the mark.
version: 3.0.0
homepage: https://github.com/Nebulino/Scrobblenaut
issue_tracker: https://github.com/Nebulino/Scrobblenaut/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  json_annotation: ^4.8.1
  convert: ^3.1.1
  dio: ^5.5.0+1
  crypto: ^3.0.3
  xml: ^6.5.0

dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.7.1
  lints: ^4.0.0
  test: ^1.25.8
